### ISSUE TITLE
PSService.ps1 starts in Local System Account, not in another account : error 1053

### ISSUE THREAD

**Issue by gggregg** [JFLarvoire/SysToolsLib#11]
Greetings,
Using PSService1.ps (unmodified), I can start it when in Local System Account. The starting takes only a few seconds.
But when in another account, starting is long and ends with an error 1053 :-(
The accounts I use are full administrators.
How can I avoid this problem ?

Sincerely,
Gaël GREGOIRE

**Comment by gggregg** [comment]
Update : if I change the arguments and add "-NoInteractive" to that line : 

p.StartInfo.Arguments = "-ExecutionPolicy Bypass –NoInteractive -c & '$scriptCopyCname' -Start"; // Works if path has spaces, but not if it contains ' quotes.

then it starts and the status becomes "running". But the Powershell code is not called.

**Comment by JFLarvoire** [comment]
This should be fixed by the latest changes in commits c72ce058a192bba9381e5fd020d1edaab3740486 and f6d8894abaec80faa1edcaf74ce261402dcbeef9.
