### ISSUE TITLE
Clarify how to use PSService.ps1

### ISSUE THREAD

**Issue by PaulWalkerUK** [JFLarvoire/SysToolsLib#16]
Please can you confirm my understanding of how to implement PSService.ps1?

Am I right in thinking I put my "application code" within the [`TimerTick` event handler](https://github.com/JFLarvoire/SysToolsLib/blob/63373f27a1b093218509c749d7aecec0cc9a4d62/PowerShell/PSService.ps1#L1105-L1107)?

If I want to change how frequently it runs, I just change the [`$period`](https://github.com/JFLarvoire/SysToolsLib/blob/63373f27a1b093218509c749d7aecec0cc9a4d62/PowerShell/PSService.ps1#L1071) variable?

The only other things to change are the script name (becomes the service name) and the [service display name and description](https://github.com/JFLarvoire/SysToolsLib/blob/63373f27a1b093218509c749d7aecec0cc9a4d62/PowerShell/PSService.ps1#L275-L276)?

**Comment by JFLarvoire** [comment]
If all you need is code that runs periodically, for example for monitoring something periodically, yes this is all what you have to do.

If you need something more reactive, for example to write a Web server in PowerShell, then you'll have to create worker threads that wait for network packets, and distribute tasks to other threads. All the bricks for doing it are there. But please don't ask me for more details. That's your problem, not mine :-)

**Comment by PaulWalkerUK** [comment]
That's great, thanks
