### ISSUE TITLE
Get-Console.ps1 error

### ISSUE THREAD

**Issue by he852100** [JFLarvoire/SysToolsLib#25]
```powershell
PS /root/tools> ./Get-Console          
MethodInvocationException: /root/tools/Get-Console.ps1
Line |                                                         
 306 |   $buffer = $Host.UI.RawUI.GetBufferContents($rec)
     |   ^ Exception calling "GetBufferContents" with "1"
     | argument(s): "The method or operation is not                
     | implemented."

InvalidOperation: /root/tools/Get-Console.ps1
Line |
 312 |     $c = $buffer[$iLastLine, $j].Character
     |     ^ Cannot index into a null array.                  
InvalidOperation: /root/tools/Get-Console.ps1
Line |                                                         
 312 |     $c = $buffer[$iLastLine, $j].Character
     |     ^ Cannot index into a null array.
```
```powershell
PSVersion                      7.0.0-daily.20191206
PSEdition                      Core
GitCommitId                    7.0.0-daily.20191206           
OS                             Linux 4.9.112-perf #1 SMP PRE… Platform
Unix
```

**Comment by JFLarvoire** [comment]
Interesting issue: I had never tested any of my PowerShell scripts in PS Core for Linux.
Juste in case, I first checked the script with PS Core 7.0.0-preview.6 in Windows: It works fine, both in the old Console, and in the new Terminal.
Then indeed with PS Core for Linux in an LXSS bash window, I get the same exception that you got.
But I'm afraid this is not a problem in Get-Console.ps1, but rather it's a problem in PS core for Linux, or more likely in .NET Core for Linux: Obviously it's still missing APIs compared to the Windows version.
I think you should post this instead in [PS Core issues](https://github.com/PowerShell/PowerShell/issues) or in [.NET Core issues](https://github.com/dotnet/core/issues).
