### ISSUE TITLE
PSService.ps1 Question

### ISSUE THREAD

**Issue by johndoe99** [JFLarvoire/SysToolsLib#26]
I have a script that requires to arguments to be passed in at the command line when the script is run. Is that possible with this script and if so how would I go about doing it?

**Comment by JFLarvoire** [comment]
By definition, a service starts up automatically. So you can't pass it command-line parameters.
But you can define a configuration file, that it reads when it starts, and that contains user-defined parameters.
Alternatively, you can store options in the registry.
