### ISSUE TITLE
PSService - Stop on shutdown

### ISSUE THREAD

**Issue by webalexeu** [JFLarvoire/SysToolsLib#32]
Hello,

It seems that service is not stopping properly when we shutdown the server (Working fine when we stop the service manually)
I don't see the stop going in SCMStop neither the exit message send to the pipe, only actions coming from finally loop.

Is this a known issue?
Second question, do you plan to integrate the pre-shutdown notification?

Thank you for your work

**Comment by webalexeu** [comment]
OnShutdown method is not implemented and that's probably explaining the behaviour

**Comment by Daymarvi** [comment]
Hello @JFLarvoire ,
together with @webalexeu we worked on the code to add the OnShutdown() and the "OnPreShutdown()"

https://github.com/JFLarvoire/SysToolsLib/pull/33

**Comment by JFLarvoire** [comment]
I've merged in PR #33, and implemented most of the changes proposed in [#issuecomment-1112394038.](https://github.com/JFLarvoire/SysToolsLib/pull/33#issuecomment-1112394038)
